[package]
name = "nucleusd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Libs
nucleus-mesh = { path = "../nucleus-mesh" }

# Packages
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", optional = true }
bluer = { version = "0.17", features = ["full"] }  # BLE
axum = "0.8"                         # HTTP + WebSocket
tower = "0.5"                        # middleware
serde = { workspace = true }
serde_json.workspace = true
postcard = { version = "1", features = ["alloc"] }  # компактная бинарная сериализация для команд
uuid = { version = "1", features = ["v4", "macro-diagnostics"] }         # генерация UUID сервиса
tracing = { workspace = true }
tracing-subscriber = "0.3"          # вывод логов
tracing-appender = "0.2"           # rolling logs
anyhow = "1"                        # удобная обработка ошибок
mdns-sd = "0.19"                     # mDNS
rumqttc = "0.25"                    # MQTT клиент
thiserror = "2"
libc = "0.2"
dbus = { version = "0.9", features = ["futures"], optional = true }
dbus-tokio = { version = "0.7", optional = true }
dbus-crossroads = { version = "0.5", optional = true }
futures = "0.3"
pin-project = { version = "1", optional = true }
