[package]
name = "nucleus-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Libs
nucleus-mesh = { path = "../nucleus-mesh" }

# Packages
serde = { workspace = true, default-features = false, features = ["alloc", "derive"] }
postcard = { version = "1", features = ["alloc"] }
async-trait = "0.1"
thiserror = { version = "2",  default-features = false }
hashbrown = { version = "0.17", default-features = false, features = ["alloc"] }
